"""empty message

Revision ID: 4ea3998ecb84
Revises: 
Create Date: 2025-05-03 19:19:13.732878

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "4ea3998ecb84"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("recipe_material", schema=None) as batch_op:
        batch_op.alter_column(
            "set_point",
            existing_type=mysql.DECIMAL(precision=10, scale=2),
            type_=sa.Float(),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "actual",
            existing_type=mysql.DECIMAL(precision=10, scale=2),
            type_=sa.Float(),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "margin",
            existing_type=mysql.DECIMAL(precision=5, scale=2),
            type_=sa.Float(),
            existing_nullable=True,
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("recipe_material", schema=None) as batch_op:
        batch_op.alter_column(
            "margin",
            existing_type=sa.Float(),
            type_=mysql.DECIMAL(precision=5, scale=2),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "actual",
            existing_type=sa.Float(),
            type_=mysql.DECIMAL(precision=10, scale=2),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "set_point",
            existing_type=sa.Float(),
            type_=mysql.DECIMAL(precision=10, scale=2),
            existing_nullable=True,
        )

    # ### end Alembic commands ###
